apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: taskapp
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: taskapp
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/ts-a-devops/taskapp-backend:26da2b0@sha256:05a9b78302a07d572f40814b659e7fe738c9dc87d6e1a01372cad8c42d7273d
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              value: "postgresql://taskapp:taskapp123@postgres-service.taskapp.svc.cluster.local:5432/taskdb"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: taskapp
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: taskapp
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/ts-a-devops/taskapp-frontend:26da2b0@sha256:05a9b78302a07d572f40814b659e7fe738c9dc87d6e1a01372cad8c42d7273d
          ports:
            - containerPort: 80
