[control_plane]
34.200.225.94 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[workers]
13.220.45.133 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
3.236.176.133 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[k3s_cluster:children]
control_plane
workers
